// Writes contract ABIs and known deployments into the app as typed TypeScript.
// Usage: npm run export-abis
const fs = require("fs");
const path = require("path");

const ARTIFACTS = path.join(__dirname, "..", "artifacts", "src");
const OUT_DIR = path.join(__dirname, "..", "..", "web", "src", "generated", "vaults");
const CONTRACTS = {
  vaultAbi: "VaultStockfill.sol/VaultStockfill.json",
  borrowDeskAbi: "BorrowDeskStockfill.sol/BorrowDeskStockfill.json",
  basketProgramAbi: "programs/BasketStockfill.sol/BasketStockfill.json",
  fillTokenAbi: "TokenStockfill.sol/TokenStockfill.json",
  buyBurnAbi: "BuyBurnStockfill.sol/BuyBurnStockfill.json",
  feeRouterAbi: "FeeRouterStockfill.sol/FeeRouterStockfill.json",
  vaultRegistryAbi: "RegistryStockfill.sol/RegistryStockfill.json",
  vaultOracleAbi: "OracleStockfill.sol/OracleStockfill.json",
  vaultPositionV4Abi: "v4/PositionStockfill.sol/PositionStockfill.json",
};

fs.mkdirSync(OUT_DIR, { recursive: true });

let abis = "// Generated by vaults/scripts/export-abis.js. Do not edit.\n\n";
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, file), "utf8"));
  abis += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(path.join(OUT_DIR, "abis.ts"), abis);

const deployments = {};
const dir = path.join(__dirname, "..", "deployments");
if (fs.existsSync(dir)) {
  for (const f of fs.readdirSync(dir).filter((f) => f === "robinhood.json" || f === "localhost.json")) {
    const d = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    if (d.network === "hardhat") continue;
    deployments[d.chainId] = d;
  }
}
fs.writeFileSync(
  path.join(OUT_DIR, "deployments.ts"),
  "// Generated by vaults/scripts/export-abis.js. Do not edit.\n\n" +
    `export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n\n` +
    `export type Deployment = {
  network: string;
  chainId: number;
  usdg: \`0x\${string}\`;
  fillToken: \`0x\${string}\` | null;
  oracle: \`0x\${string}\`;
  feeRouter: \`0x\${string}\`;
  buyBurn: \`0x\${string}\`;
  registry: \`0x\${string}\`;
  basketProgram: \`0x\${string}\`;
  vaults: Record<string, { vault: \`0x\${string}\`; position: \`0x\${string}\`; equityToken: \`0x\${string}\`; name: string }>;
  creditLines: Record<string, \`0x\${string}\`>;
  [key: string]: unknown;
};\n`
);
const config = require("../config/robinhood.json");
const catalog = {
  chainId: config.network.chainId,
  usdg: config.tokens.usdg.address,
  equityTokens: Object.fromEntries(
    Object.entries(config.equityTokens).map(([t, v]) => [t, { name: v.name, address: v.address }])
  ),
  launchVaults: config.launch.vaults,
  launchCreditLines: config.launch.creditLines,
  heldValueCapUsdg: config.launch.heldValueCapUsdg,
};
fs.writeFileSync(
  path.join(OUT_DIR, "catalog.ts"),
  "// Generated by vaults/scripts/export-abis.js. Do not edit.\n\n" +
    `export const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`
);

console.log(`Exported ${Object.keys(CONTRACTS).length} ABIs and ${Object.keys(deployments).length} deployment(s) to ${OUT_DIR}`);

